### ISSUE TITLE
No work?

### ISSUE THREAD

**Issue by benzeji** [instafluff/ChatterboxTranslatorBot#37]
C:\Users\Romario\BotTranslate>npm start

> chatterboxtranslatorbot@1.0.1 start
> node .

[ '#[romestnik]' ]
C:\Users\Romario\BotTranslate\app.js:38
                let existing = result.data.map( x => x.login );
                                           ^

TypeError: Cannot read properties of undefined (reading 'map')
    at C:\Users\Romario\BotTranslate\app.js:38:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error

**Comment by neoacevedo** [comment]
I think this project is stopped or dead.
